stages:
  - build
  - deploy

variables:
  CI_REGISTRY: gitlab.flextech.asia:5050
  IMAGE_TAG: $CI_REGISTRY/lucky-playlot/os-app-admin-api:$CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - echo $IMAGE_TAG-$CI_COMMIT_SHORT_SHA
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -t $IMAGE_TAG-$CI_COMMIT_SHORT_SHA -f dockerfiles/Prod/Dockerfile .
    - docker push $IMAGE_TAG-$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_TAG
  only:
    - developx
    - masterx
    - stagingx

deploy_develop:
  stage: deploy
  script:
    - echo image_tag $IMAGE_TAG ci_commit $CI_COMMIT_SHORT_SHA
    - sshpass -p $SERVER_PASS_7 ssh $SERVER_USER_7@$SERVER_HOST_7 "docker-compose pull $APP_NAME && docker-compose up --force-recreate -d $APP_NAME"
  environment:
    name: develop
  only:
    - developx
